# For more information: https://laravel.com/docs/sail
version: '3'
services:
    hd_app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - hd_network
            - default
        depends_on:
            - hd_db
            - hd_redis
    hd_db:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'hd_db:/var/lib/mysql'
        networks:
            - hd_network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    hd_redis:
        image: 'redis:alpine'
        volumes:
            - 'hd_redis:/data'
        networks:
            - hd_network
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    hd_mailhog:
            image: 'mailhog/mailhog:latest'
            ports:
              - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
            networks:
              - hd_network
networks:
    hd_network:
        driver: bridge
    default:
            external:
                    name: nginx_proxy
volumes:
    hd_db:
        driver: local
    hd_redis:
        driver: local
