<?php

namespace Tests\Feature;

use App\Models\User;
use Database\Seeders\PermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class RolesTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(PermissionSeeder::class);
    }

    /**
     * 1. A user can be assigned to the "restricted user" role
    2. A user can be assigned to the "user" role
    3. A user can be assigned to the "manager" role
    4. A user can be assigned to the "agent" role
    5. A user can be assigned to the "admin" role
    6. A user can be assigned to the "super-admin" role

     *
     * @return void
     */
    public function test_user_can_be_assigned_to_restricted_user_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('restricted user');

        $this->assertTrue($user->hasRole('restricted user'));
    }

    public function test_user_can_be_assigned_to_user_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('user');

        $this->assertTrue($user->hasRole('user'));
    }

    public function test_user_can_be_assigned_to_manager_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('manager');

        $this->assertTrue($user->hasRole('manager'));
    }

    public function test_user_can_be_assigned_to_agent_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('agent');

        $this->assertTrue($user->hasRole('agent'));
    }

    public function test_user_can_be_assigned_to_admin_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('admin');

        $this->assertTrue($user->hasRole('admin'));
    }

    public function test_user_can_be_assigned_to_super_admin_role(): void
    {
        $user = User::factory()
            ->create()
            ->assignRole('super-admin');

        $this->assertTrue($user->hasRole('super-admin'));
    }
}
